### ISSUE TITLE
Migrating keyring database

### ISSUE THREAD

**Issue by mixmix** [ssbc/ssb-tribes#89]
In upgrading `ssb-keyring` we need to remember that in Ahau people already have a keyring database in place.
- [x] check if there have been mutations to the data structure of that db
- [x] write a migration for old > new format

**Comment by Powersource** [comment]
possible inspiration https://www.npmjs.com/package/ssb-migrate

**Comment by Powersource** [comment]
MR https://gitlab.com/ahau/lib/ssb-keyring/-/merge_requests/30

**Comment by Powersource** [comment]
MR ready for review
